apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GitOps Demo</title>
        <style>
            body { font-family: Arial; margin: 40px; }
            .info { background: #e3f2fd; padding: 20px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <h1>GitOps Demo with ArgoCD</h1>
        <div class="info">
            <p><strong>Deployed by:</strong> ArgoCD</p>
            <p><strong>Monitoring:</strong> Prometheus + Grafana</p>
            <p><strong>Platform:</strong> AWS EKS</p>
            <p><strong>Namespace:</strong> webapp</p>
        </div>
    </body>
    </html>